#version: '3.8'

#services:
#  app:
#    build: .
#    container_name: microservicio-diario
#    ports:
#      - "8081:8081"
#    environment:
#      - DB_URL=${DB_URL}
#      - DB_USERNAME=${DB_USERNAME}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - JWT_SECRET=${jwt.secret}
#    env_file:
#      - .env
#    restart: unless-stopped
#    networks:
#      - app-network

#networks:
#  app-network:
#    driver: bridge

services:
  microservicio-notificaciones:
    build: .
    container_name: microservicio-notificaciones
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      # Pasamos la conexión de Azure directa a Spring
      # URL JDBC Completa (Esto es lo que Java necesita)
      - DB_URL=jdbc:sqlserver://sanity.database.windows.net:1433;database=notificaciones-db;user=Admin123@sanity;password=Password$;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

      # Usuario y Contraseña mapeados a las variables correctas
      - DB_USERNAME=Admin123@sanity
      - DB_PASSWORD=Password$

      # Seguridad JWT
      - JWT_SECRET=B8/aV2WyX9TCH+r0hLSOdZI4f5k6bEwnxJ3qM/o2u+A3cR9gHIV7yK0pLwU8iZ/jl+eS6wY5nB7tD/fRz8kE/g==
      # Valor en milisegundos (ejemplo: 1 día = 86400000)
      - JWT_EXPIRATION=86400000

      # Configuración SMTP (Email)
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=sanity.ayuda@gmail.com
      - SMTP_PASSWORD=chofgpxkhtclhvrt

    restart: unless-stopped
