#version: '3.8'

#services:
#  app:
#    build: .
#    container_name: microservicio-diario
#    ports:
#      - "8081:8081"
#    environment:
#      - DB_URL=${DB_URL}
#      - DB_USERNAME=${DB_USERNAME}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - JWT_SECRET=${jwt.secret}
#    env_file:
#      - .env
#    restart: unless-stopped
#    networks:
#      - app-network

#networks:
#  app-network:
#    driver: bridge

services:
  microservicio-notificaciones:
    build: .
    container_name: microservicio-notificaciones
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      # Pasamos la conexión de Azure directa a Spring
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      
      # Azure Communication Services (Email)
      - ACS_CONNECTION_STRING=${ACS_CONNECTION_STRING}
      - ACS_SENDER_EMAIL=${ACS_SENDER_EMAIL}

      # SOLUCIÓN AL ERROR: Pasamos las variables conflictivas como JSON
      # Esto inyecta jwt.secret y jwt.expiration correctamente en tu JwtService.java
      - SPRING_APPLICATION_JSON={"jwt.secret":"${JWT_SECRET}", "jwt.expiration":"${JWT_EXPIRATION}"}

    restart: unless-stopped
