package com.example.microservicionotificaciones.servicios;

import com.example.microservicionotificaciones.dto.LoginRequestDTO;
import com.example.microservicionotificaciones.dto.LoginResponseDTO;
import com.example.microservicionotificaciones.modelos.Usuario;
import com.example.microservicionotificaciones.dto.PreferenciasDTO;
import com.example.microservicionotificaciones.repositorios.UsuarioRepository;
import com.example.microservicionotificaciones.seguridad.JwtService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class UsuarioService {

    @Autowired
    private UsuarioRepository usuarioRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private JwtService jwtService;

    @Autowired
    @Lazy // Usamos Lazy para evitar problemas de dependencias circulares
    private AuthenticationManager authenticationManager;

    @Autowired
    private UserDetailsServiceImpl userDetailsService;

    @Autowired
    private EmailService emailService;

    // --- REGISTRAR USUARIO ---
    public Usuario createUsuario(Usuario usuario) {
        // Encriptamos la contraseña antes de guardar
        usuario.setPassword(passwordEncoder.encode(usuario.getPassword()));
        Usuario nuevoUsuario = usuarioRepository.save(usuario);

        // Enviar email de bienvenida (no bloqueante)
        try {
            emailService.enviarEmailBienvenida(nuevoUsuario.getEmail(), nuevoUsuario.getNombre());
        } catch (Exception e) {
            // Log del error pero no bloquear el registro
            System.err.println("Error al enviar email de bienvenida: " + e.getMessage());
        }

        return nuevoUsuario;
    }

    // --- LOGIN (Generar Token) ---
    public LoginResponseDTO login(LoginRequestDTO loginRequest) {
        // 1. Validar credenciales (Spring Security lo hace por nosotros)
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(
                        loginRequest.getEmail(),
                        loginRequest.getPassword()));

        // 2. Si pasó la autenticación, cargamos los detalles del usuario
        UserDetails userDetails = userDetailsService.loadUserByUsername(loginRequest.getEmail());

        // 3. Generamos el Token
        String token = jwtService.generateToken(userDetails);

        return new LoginResponseDTO(token);
    }

    // Método auxiliar para buscar usuario por ID
    public Optional<Usuario> getUsuarioById(String id) {
        return usuarioRepository.findById(id);
    }

    // Método auxiliar para listar todos (opcional)
    public List<Usuario> getAllUsuarios() {
        return usuarioRepository.findAll();
    }

    // --- ACTUALIZAR PREFERENCIAS ---
    public Usuario updatePreferencias(String id, PreferenciasDTO dto) {
        Optional<Usuario> optionalUsuario = usuarioRepository.findById(id);
        if (optionalUsuario.isPresent()) {
            Usuario usuario = optionalUsuario.get();
            usuario.setPushEnabled(dto.isPushEnabled());
            usuario.setEmailEnabled(dto.isEmailEnabled());
            usuario.setRecordatoriosCitas(dto.isRecordatoriosCitas());
            usuario.setRecordatoriosActividades(dto.isRecordatoriosActividades());
            usuario.setRecordatoriosHabitos(dto.isRecordatoriosHabitos());
            usuario.setNuevasActividades(dto.isNuevasActividades());
            usuario.setMensajesIa(dto.isMensajesIa());
            return usuarioRepository.save(usuario);
        }
        throw new RuntimeException("Usuario no encontrado con ID: " + id);
    }
    
    // --- OBTENER O AUTO-CREAR USUARIO ---
    public Usuario getUsuarioOAutoCrear(String id, String email) {
        return usuarioRepository.findById(id).orElseGet(() -> {
            String targetEmail = (email != null && !email.isBlank()) ? email : (id.contains("@") ? id : id + "@autogenerated.com");
            Usuario nuevo = new Usuario();
            nuevo.setId(id);
            nuevo.setEmail(targetEmail);
            nuevo.setNombre(targetEmail.split("@")[0]);
            nuevo.setPassword("EXTERNAL_USER");
            return usuarioRepository.save(nuevo);
        });
    }

    // --- ACTUALIZAR PREFERENCIAS CON AUTO-CREACIÓN ---
    public Usuario updatePreferenciasOAutoCrear(String id, String email, PreferenciasDTO dto) {
        Usuario usuario = getUsuarioOAutoCrear(id, email);
        usuario.setPushEnabled(dto.isPushEnabled());
        usuario.setEmailEnabled(dto.isEmailEnabled());
        usuario.setRecordatoriosCitas(dto.isRecordatoriosCitas());
        usuario.setRecordatoriosActividades(dto.isRecordatoriosActividades());
        usuario.setRecordatoriosHabitos(dto.isRecordatoriosHabitos());
        usuario.setNuevasActividades(dto.isNuevasActividades());
        usuario.setMensajesIa(dto.isMensajesIa());
        return usuarioRepository.save(usuario);
    }
}